<?php
/*
 * Copyright (c) 2023 Payfast (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */

?>
<h2><?=
    /** @noinspection PhpUndefinedVariableInspection */
    $block->escapeHtml($block->getMessage()); ?></h2>
<p>Redirecting to Paygate...</p>
<form class="checkout" name="<?= $block->escapeHtml($block->getName()); ?>"
      id="<?=
        $block->escapeHtml($block->getId()); ?>"
      action="<?=
        $block->escapeHtml($block->getFormAction()); ?>"
      method="post" class="multicheckout">
    <?php
    foreach ($block->getFormData() as $item => $value): ?>
        <input type="hidden" name="<?=
        $block->escapeHtml($item); ?>" value="<?=
        $block->escapeHtml($value); ?>" size="200">
        <?php
    endforeach; ?>
</form>
<?= /* @noEscape */ $block->getSubmitForm();?>
