<?php
/*
 * Copyright (c) 2023 Payfast (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */

namespace PayGate\PayWeb\Model;

use JetBrains\PhpStorm\Pure;

class CountryData
{
    /**
     * Merge 2 country splits and return
     *
     * @return array
     */
    #[Pure] public function getCountries(): array
    {
        return array_merge($this->getCountriesAToM(), $this->getCountriesNToZ());
    }

    /**
     * Split list part 1
     *
     * @return array[]
     */
    private function getCountriesAToM(): array
    {
        return [
            "AD" => ["ANDORRA", "AD", "AND", "020"],
            "AE" => ["UNITED ARAB EMIRATES", "AE", "ARE", "784"],
            "AF" => ["AFGHANISTAN", "AF", "AFG", "004"],
            "AG" => ["ANTIGUA AND BARBUDA", "AG", "ATG", "028"],
            "AI" => ["ANGUILLA", "AI", "AIA", "660"],
            "AL" => ["ALBANIA", "AL", "ALB", "008"],
            "AM" => ["ARMENIA", "AM", "ARM", "051"],
            "AN" => ["NETHERLANDS ANTILLES", "AN", "ANT", "530"],
            "AO" => ["ANGOLA", "AO", "AGO", "024"],
            "AQ" => ["ANTARCTICA", "AQ", "ATA", "010"],
            "AR" => ["ARGENTINA", "AR", "ARG", "032"],
            "AS" => ["AMERICAN SAMOA", "AS", "ASM", "016"],
            "AT" => ["AUSTRIA", "AT", "AUT", "040"],
            "AU" => ["AUSTRALIA", "AU", "AUS", "036"],
            "AW" => ["ARUBA", "AW", "ABW", "533"],
            "AZ" => ["AZERBAIJAN", "AZ", "AZE", "031"],
            "BA" => ["BOSNIA AND HERZEGOVINA", "BA", "BIH", "070"],
            "BB" => ["BARBADOS", "BB", "BRB", "052"],
            "BD" => ["BANGLADESH", "BD", "BGD", "050"],
            "BE" => ["BELGIUM", "BE", "BEL", "056"],
            "BF" => ["BURKINA FASO", "BF", "BFA", "854"],
            "BG" => ["BULGARIA", "BG", "BGR", "100"],
            "BH" => ["BAHRAIN", "BH", "BHR", "048"],
            "BI" => ["BURUNDI", "BI", "BDI", "108"],
            "BJ" => ["BENIN", "BJ", "BEN", "204"],
            "BM" => ["BERMUDA", "BM", "BMU", "060"],
            "BN" => ["BRUNEI DARUSSALAM", "BN", "BRN", "096"],
            "BO" => ["BOLIVIA", "BO", "BOL", "068"],
            "BR" => ["BRAZIL", "BR", "BRA", "076"],
            "BS" => ["BAHAMAS", "BS", "BHS", "044"],
            "BT" => ["BHUTAN", "BT", "BTN", "064"],
            "BV" => ["BOUVET ISLAND", "BV", "BVT", "074"],
            "BW" => ["BOTSWANA", "BW", "BWA", "072"],
            "BY" => ["BELARUS", "BY", "BLR", "112"],
            "BZ" => ["BELIZE", "BZ", "BLZ", "084"],
            "CA" => ["CANADA", "CA", "CAN", "124"],
            "CC" => ["COCOS (KEELING) ISLANDS", "CC", "CCK", "166"],
            "CF" => ["CENTRAL AFRICAN REPUBLIC", "CF", "CAF", "140"],
            "CG" => ["CONGO", "CG", "COG", "178"],
            "CH" => ["SWITZERLAND", "CH", "CHE", "756"],
            "CI" => ["COTE D'IVOIRE", "CI", "CIV", "384"],
            "CK" => ["COOK ISLANDS", "CK", "COK", "184"],
            "CL" => ["CHILE", "CL", "CHL", "152"],
            "CM" => ["CAMEROON", "CM", "CMR", "120"],
            "CN" => ["CHINA", "CN", "CHN", "156"],
            "CO" => ["COLOMBIA", "CO", "COL", "170"],
            "CR" => ["COSTA RICA", "CR", "CRI", "188"],
            "CU" => ["CUBA", "CU", "CUB", "192"],
            "CV" => ["CAPE VERDE", "CV", "CPV", "132"],
            "CX" => ["CHRISTMAS ISLAND", "CX", "CXR", "162"],
            "CY" => ["CYPRUS", "CY", "CYP", "196"],
            "CZ" => ["CZECH REPUBLIC", "CZ", "CZE", "203"],
            "DE" => ["GERMANY", "DE", "DEU", "276"],
            "DJ" => ["DJIBOUTI", "DJ", "DJI", "262"],
            "DK" => ["DENMARK", "DK", "DNK", "208"],
            "DM" => ["DOMINICA", "DM", "DMA", "212"],
            "DO" => ["DOMINICAN REPUBLIC", "DO", "DOM", "214"],
            "DZ" => ["ALGERIA", "DZ", "DZA", "012"],
            "EC" => ["ECUADOR", "EC", "ECU", "218"],
            "EE" => ["ESTONIA", "EE", "EST", "233"],
            "EG" => ["EGYPT", "EG", "EGY", "818"],
            "EH" => ["WESTERN SAHARA", "EH", "ESH", "732"],
            "ER" => ["ERITREA", "ER", "ERI", "232"],
            "ES" => ["SPAIN", "ES", "ESP", "724"],
            "ET" => ["ETHIOPIA", "ET", "ETH", "210"],
            "FI" => ["FINLAND", "FI", "FIN", "246"],
            "FJ" => ["FIJI", "FJ", "FJI", "242"],
            "FK" => ["FALKLAND ISLANDS (MALVINAS)", "FK", "FLK", "238"],
            "FM" => ["MICRONESIA, FEDERATED STATES OF", "FM", "FSM", "583"],
            "FO" => ["FAROE ISLANDS", "FO", "FRO", "234"],
            "FR" => ["FRANCE", "FR", "FRA", "250"],
            "FX" => ["FRANCE, METROPOLITAN", "FX", "FXX", "249"],
            "GA" => ["GABON", "GA", "GAB", "266"],
            "GB" => ["UNITED KINGDOM", "GB", "GBR", "826"],
            "GD" => ["GRENADA", "GD", "GRD", "308"],
            "GE" => ["GEORGIA", "GE", "GEO", "268"],
            "GF" => ["FRENCH GUIANA", "GF", "GUF", "254"],
            "GH" => ["GHANA", "GH", "GHA", "288"],
            "GI" => ["GIBRALTAR", "GI", "GIB", "292"],
            "GL" => ["GREENLAND", "GL", "GRL", "304"],
            "GM" => ["GAMBIA", "GM", "GMB", "270"],
            "GN" => ["GUINEA", "GN", "GIN", "324"],
            "GP" => ["GUADELOUPE", "GP", "GLP", "312"],
            "GQ" => ["EQUATORIAL GUINEA", "GQ", "GNQ", "226"],
            "GR" => ["GREECE", "GR", "GRC", "300"],
            "GT" => ["GUATEMALA", "GT", "GTM", "320"],
            "GU" => ["GUAM", "GU", "GUM", "316"],
            "GW" => ["GUINEA-BISSAU", "GW", "GNB", "624"],
            "GY" => ["GUYANA", "GY", "GUY", "328"],
            "HK" => ["HONG KONG", "HK", "HKG", "344"],
            "HM" => ["HEARD ISLAND & MCDONALD ISLANDS", "HM", "HMD", "334"],
            "HN" => ["HONDURAS", "HN", "HND", "340"],
            "HR" => ["CROATIA (local name: Hrvatska)", "HR", "HRV", "191"],
            "HT" => ["HAITI", "HT", "HTI", "332"],
            "HU" => ["HUNGARY", "HU", "HUN", "348"],
            "ID" => ["INDONESIA", "ID", "IDN", "360"],
            "IE" => ["IRELAND", "IE", "IRL", "372"],
            "IL" => ["ISRAEL", "IL", "ISR", "376"],
            "IN" => ["INDIA", "IN", "IND", "356"],
            "IO" => ["BRITISH INDIAN OCEAN TERRITORY", "IO", "IOT", "086"],
            "IQ" => ["IRAQ", "IQ", "IRQ", "368"],
            "IR" => ["IRAN, ISLAMIC REPUBLIC OF", "IR", "IRN", "364"],
            "IS" => ["ICELAND", "IS", "ISL", "352"],
            "IT" => ["ITALY", "IT", "ITA", "380"],
            "JM" => ["JAMAICA", "JM", "JAM", "388"],
            "JO" => ["JORDAN", "JO", "JOR", "400"],
            "JP" => ["JAPAN", "JP", "JPN", "392"],
            "KE" => ["KENYA", "KE", "KEN", "404"],
            "KG" => ["KYRGYZSTAN", "KG", "KGZ", "417"],
            "KH" => ["CAMBODIA", "KH", "KHM", "116"],
            "KI" => ["KIRIBATI", "KI", "KIR", "296"],
            "KM" => ["COMOROS", "KM", "COM", "174"],
            "KN" => ["SAINT KITTS AND NEVIS", "KN", "KNA", "659"],
            "KP" => ["KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KP", "PRK", "408"],
            "KR" => ["KOREA, REPUBLIC OF", "KR", "KOR", "410"],
            "KW" => ["KUWAIT", "KW", "KWT", "414"],
            "KY" => ["CAYMAN ISLANDS", "KY", "CYM", "136"],
            "KZ" => ["KAZAKHSTAN", "KZ", "KAZ", "398"],
            "LA" => ["LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LA", "LAO", "418"],
            "LB" => ["LEBANON", "LB", "LBN", "422"],
            "LC" => ["SAINT LUCIA", "LC", "LCA", "662"],
            "LI" => ["LIECHTENSTEIN", "LI", "LIE", "438"],
            "LK" => ["SRI LANKA", "LK", "LKA", "144"],
            "LR" => ["LIBERIA", "LR", "LBR", "430"],
            "LS" => ["LESOTHO", "LS", "LSO", "426"],
            "LT" => ["LITHUANIA", "LT", "LTU", "440"],
            "LU" => ["LUXEMBOURG", "LU", "LUX", "442"],
            "LV" => ["LATVIA", "LV", "LVA", "428"],
            "LY" => ["LIBYAN ARAB JAMAHIRIYA", "LY", "LBY", "434"],
            "MA" => ["MOROCCO", "MA", "MAR", "504"],
            "MC" => ["MONACO", "MC", "MCO", "492"],
            "MD" => ["MOLDOVA, REPUBLIC OF", "MD", "MDA", "498"],
            "MG" => ["MADAGASCAR", "MG", "MDG", "450"],
            "MH" => ["MARSHALL ISLANDS", "MH", "MHL", "584"],
            "MK" => ["MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "MK", "MKD", "807"],
            "ML" => ["MALI", "ML", "MLI", "466"],
            "MM" => ["MYANMAR", "MM", "MMR", "104"],
            "MN" => ["MONGOLIA", "MN", "MNG", "496"],
            "MO" => ["MACAU", "MO", "MAC", "446"],
            "MP" => ["NORTHERN MARIANA ISLANDS", "MP", "MNP", "580"],
            "MQ" => ["MARTINIQUE", "MQ", "MTQ", "474"],
            "MR" => ["MAURITANIA", "MR", "MRT", "478"],
            "MS" => ["MONTSERRAT", "MS", "MSR", "500"],
            "MT" => ["MALTA", "MT", "MLT", "470"],
            "MU" => ["MAURITIUS", "MU", "MUS", "480"],
            "MV" => ["MALDIVES", "MV", "MDV", "462"],
            "MW" => ["MALAWI", "MW", "MWI", "454"],
            "MX" => ["MEXICO", "MX", "MEX", "484"],
            "MY" => ["MALAYSIA", "MY", "MYS", "458"],
            "MZ" => ["MOZAMBIQUE", "MZ", "MOZ", "508"],
        ];
    }

    /**
     * Split list part 2
     *
     * @return array[]
     */
    private function getCountriesNToZ(): array
    {
        return [
            "NA" => ["NAMIBIA", "NA", "NAM", "516"],
            "NC" => ["NEW CALEDONIA", "NC", "NCL", "540"],
            "NE" => ["NIGER", "NE", "NER", "562"],
            "NF" => ["NORFOLK ISLAND", "NF", "NFK", "574"],
            "NG" => ["NIGERIA", "NG", "NGA", "566"],
            "NI" => ["NICARAGUA", "NI", "NIC", "558"],
            "NL" => ["NETHERLANDS", "NL", "NLD", "528"],
            "NO" => ["NORWAY", "NO", "NOR", "578"],
            "NP" => ["NEPAL", "NP", "NPL", "524"],
            "NR" => ["NAURU", "NR", "NRU", "520"],
            "NU" => ["NIUE", "NU", "NIU", "570"],
            "NZ" => ["NEW ZEALAND", "NZ", "NZL", "554"],
            "OM" => ["OMAN", "OM", "OMN", "512"],
            "PA" => ["PANAMA", "PA", "PAN", "591"],
            "PE" => ["PERU", "PE", "PER", "604"],
            "PF" => ["FRENCH POLYNESIA", "PF", "PYF", "258"],
            "PG" => ["PAPUA NEW GUINEA", "PG", "PNG", "598"],
            "PH" => ["PHILIPPINES", "PH", "PHL", "608"],
            "PK" => ["PAKISTAN", "PK", "PAK", "586"],
            "PL" => ["POLAND", "PL", "POL", "616"],
            "PM" => ["SAINT PIERRE AND MIQUELON", "PM", "SPM", "666"],
            "PN" => ["PITCAIRN", "PN", "PCN", "612"],
            "PR" => ["PUERTO RICO", "PR", "PRI", "630"],
            "PT" => ["PORTUGAL", "PT", "PRT", "620"],
            "PW" => ["PALAU", "PW", "PLW", "585"],
            "PY" => ["PARAGUAY", "PY", "PRY", "600"],
            "QA" => ["QATAR", "QA", "QAT", "634"],
            "RE" => ["REUNION", "RE", "REU", "638"],
            "RO" => ["ROMANIA", "RO", "ROU", "642"],
            "RS" => ["SERBIA", "RS", "SRB", "688"],
            "RU" => ["RUSSIAN FEDERATION", "RU", "RUS", "643"],
            "RW" => ["RWANDA", "RW", "RWA", "646"],
            "SA" => ["SAUDI ARABIA", "SA", "SAU", "682"],
            "SB" => ["SOLOMON ISLANDS", "SB", "SLB", "90"],
            "SC" => ["SEYCHELLES", "SC", "SYC", "690"],
            "SD" => ["SUDAN", "SD", "SDN", "736"],
            "SE" => ["SWEDEN", "SE", "SWE", "752"],
            "SG" => ["SINGAPORE", "SG", "SGP", "702"],
            "SH" => ["SAINT HELENA", "SH", "SHN", "654"],
            "SI" => ["SLOVENIA", "SI", "SVN", "705"],
            "SJ" => ["SVALBARD AND JAN MAYEN ISLANDS", "SJ", "SJM", "744"],
            "SK" => ["SLOVAKIA (Slovak Republic)", "SK", "SVK", "703"],
            "SL" => ["SIERRA LEONE", "SL", "SLE", "694"],
            "SM" => ["SAN MARINO", "SM", "SMR", "674"],
            "SN" => ["SENEGAL", "SN", "SEN", "686"],
            "SO" => ["SOMALIA", "SO", "SOM", "706"],
            "SR" => ["SURINAME", "SR", "SUR", "740"],
            "ST" => ["SAO TOME AND PRINCIPE", "ST", "STP", "678"],
            "SV" => ["EL SALVADOR", "SV", "SLV", "222"],
            "SY" => ["SYRIAN ARAB REPUBLIC", "SY", "SYR", "760"],
            "SZ" => ["SWAZILAND", "SZ", "SWZ", "748"],
            "TC" => ["TURKS AND CAICOS ISLANDS", "TC", "TCA", "796"],
            "TD" => ["CHAD", "TD", "TCD", "148"],
            "TF" => ["FRENCH SOUTHERN TERRITORIES", "TF", "ATF", "260"],
            "TG" => ["TOGO", "TG", "TGO", "768"],
            "TH" => ["THAILAND", "TH", "THA", "764"],
            "TJ" => ["TAJIKISTAN", "TJ", "TJK", "762"],
            "TK" => ["TOKELAU", "TK", "TKL", "772"],
            "TL" => ["EAST TIMOR", "TL", "TLS", "626"],
            "TM" => ["TURKMENISTAN", "TM", "TKM", "795"],
            "TN" => ["TUNISIA", "TN", "TUN", "788"],
            "TO" => ["TONGA", "TO", "TON", "776"],
            "TR" => ["TURKEY", "TR", "TUR", "792"],
            "TT" => ["TRINIDAD AND TOBAGO", "TT", "TTO", "780"],
            "TV" => ["TUVALU", "TV", "TUV", "798"],
            "TW" => ["TAIWAN, PROVINCE OF CHINA", "TW", "TWN", "158"],
            "TZ" => ["TANZANIA, UNITED REPUBLIC OF", "TZ", "TZA", "834"],
            "UA" => ["UKRAINE", "UA", "UKR", "804"],
            "UG" => ["UGANDA", "UG", "UGA", "800"],
            "UM" => ["UNITED STATES MINOR OUTLYING ISLANDS", "UM", "UMI", "581"],
            "US" => ["UNITED STATES", "US", "USA", "840"],
            "UY" => ["URUGUAY", "UY", "URY", "858"],
            "UZ" => ["UZBEKISTAN", "UZ", "UZB", "860"],
            "VA" => ["VATICAN CITY STATE (HOLY SEE)", "VA", "VAT", "336"],
            "VC" => ["SAINT VINCENT AND THE GRENADINES", "VC", "VCT", "670"],
            "VE" => ["VENEZUELA", "VE", "VEN", "862"],
            "VG" => ["VIRGIN ISLANDS (BRITISH)", "VG", "VGB", "92"],
            "VI" => ["VIRGIN ISLANDS (U.S.)", "VI", "VIR", "850"],
            "VN" => ["VIET NAM", "VN", "VNM", "704"],
            "VU" => ["VANUATU", "VU", "VUT", "548"],
            "WF" => ["WALLIS AND FUTUNA ISLANDS", "WF", "WLF", "876"],
            "WS" => ["SAMOA", "WS", "WSM", "882"],
            "YE" => ["YEMEN", "YE", "YEM", "887"],
            "YT" => ["MAYOTTE", "YT", "MYT", "175"],
            "YU" => ["YUGOSLAVIA", "YU", "YUG", "891"],
            "ZA" => ["SOUTH AFRICA", "ZA", "ZAF", "710"],
            "ZM" => ["ZAMBIA", "ZM", "ZMB", "894"],
            "ZR" => ["ZAIRE", "ZR", "ZAR", "180"],
            "ZW" => ["ZIMBABWE", "ZW", "ZWE", "716"],
        ];
    }
}
