<?php
/*
 * Copyright (c) 2019 PayGate (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 * 
 * Released under the GNU General Public License
 */
?>
<h2><?php echo $this->escapeHtml($this->getMessage()); ?></h2>

<form name="<?php echo $this->escapeHtml($this->getName()); ?>"
      id="<?php echo $this->escapeHtml($this->getId()); ?>"
      action="<?php echo $this->escapeHtml($this->getFormAction()); ?>"
      method="post">

    <?php foreach($this->getFormData() as $item => $value ): ?>
        <input type="hidden" name="<?php echo $this->escapeHtml($item); ?>" value="<?php echo $this->escapeHtml($value); ?>" size="200">
    <?php endforeach; ?>
</form>
<?php echo $this->getSubmitForm(); ?>
