<?php
/*
 * Copyright (c) 2021 PayGate (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */

namespace PayGate\PayWeb\Model;

class CountryData
{

    public static function getCountries(): array
    {
        return array_merge(self::getCountriesAToM(), self::getCountriesNToZ());
    }

    private static function getCountriesAToM(): array
    {
        return array(
            "AD" => array("ANDORRA", "AD", "AND", "020"),
            "AE" => array("UNITED ARAB EMIRATES", "AE", "ARE", "784"),
            "AF" => array("AFGHANISTAN", "AF", "AFG", "004"),
            "AG" => array("ANTIGUA AND BARBUDA", "AG", "ATG", "028"),
            "AI" => array("ANGUILLA", "AI", "AIA", "660"),
            "AL" => array("ALBANIA", "AL", "ALB", "008"),
            "AM" => array("ARMENIA", "AM", "ARM", "051"),
            "AN" => array("NETHERLANDS ANTILLES", "AN", "ANT", "530"),
            "AO" => array("ANGOLA", "AO", "AGO", "024"),
            "AQ" => array("ANTARCTICA", "AQ", "ATA", "010"),
            "AR" => array("ARGENTINA", "AR", "ARG", "032"),
            "AS" => array("AMERICAN SAMOA", "AS", "ASM", "016"),
            "AT" => array("AUSTRIA", "AT", "AUT", "040"),
            "AU" => array("AUSTRALIA", "AU", "AUS", "036"),
            "AW" => array("ARUBA", "AW", "ABW", "533"),
            "AZ" => array("AZERBAIJAN", "AZ", "AZE", "031"),
            "BA" => array("BOSNIA AND HERZEGOVINA", "BA", "BIH", "070"),
            "BB" => array("BARBADOS", "BB", "BRB", "052"),
            "BD" => array("BANGLADESH", "BD", "BGD", "050"),
            "BE" => array("BELGIUM", "BE", "BEL", "056"),
            "BF" => array("BURKINA FASO", "BF", "BFA", "854"),
            "BG" => array("BULGARIA", "BG", "BGR", "100"),
            "BH" => array("BAHRAIN", "BH", "BHR", "048"),
            "BI" => array("BURUNDI", "BI", "BDI", "108"),
            "BJ" => array("BENIN", "BJ", "BEN", "204"),
            "BM" => array("BERMUDA", "BM", "BMU", "060"),
            "BN" => array("BRUNEI DARUSSALAM", "BN", "BRN", "096"),
            "BO" => array("BOLIVIA", "BO", "BOL", "068"),
            "BR" => array("BRAZIL", "BR", "BRA", "076"),
            "BS" => array("BAHAMAS", "BS", "BHS", "044"),
            "BT" => array("BHUTAN", "BT", "BTN", "064"),
            "BV" => array("BOUVET ISLAND", "BV", "BVT", "074"),
            "BW" => array("BOTSWANA", "BW", "BWA", "072"),
            "BY" => array("BELARUS", "BY", "BLR", "112"),
            "BZ" => array("BELIZE", "BZ", "BLZ", "084"),
            "CA" => array("CANADA", "CA", "CAN", "124"),
            "CC" => array("COCOS (KEELING) ISLANDS", "CC", "CCK", "166"),
            "CF" => array("CENTRAL AFRICAN REPUBLIC", "CF", "CAF", "140"),
            "CG" => array("CONGO", "CG", "COG", "178"),
            "CH" => array("SWITZERLAND", "CH", "CHE", "756"),
            "CI" => array("COTE D'IVOIRE", "CI", "CIV", "384"),
            "CK" => array("COOK ISLANDS", "CK", "COK", "184"),
            "CL" => array("CHILE", "CL", "CHL", "152"),
            "CM" => array("CAMEROON", "CM", "CMR", "120"),
            "CN" => array("CHINA", "CN", "CHN", "156"),
            "CO" => array("COLOMBIA", "CO", "COL", "170"),
            "CR" => array("COSTA RICA", "CR", "CRI", "188"),
            "CU" => array("CUBA", "CU", "CUB", "192"),
            "CV" => array("CAPE VERDE", "CV", "CPV", "132"),
            "CX" => array("CHRISTMAS ISLAND", "CX", "CXR", "162"),
            "CY" => array("CYPRUS", "CY", "CYP", "196"),
            "CZ" => array("CZECH REPUBLIC", "CZ", "CZE", "203"),
            "DE" => array("GERMANY", "DE", "DEU", "276"),
            "DJ" => array("DJIBOUTI", "DJ", "DJI", "262"),
            "DK" => array("DENMARK", "DK", "DNK", "208"),
            "DM" => array("DOMINICA", "DM", "DMA", "212"),
            "DO" => array("DOMINICAN REPUBLIC", "DO", "DOM", "214"),
            "DZ" => array("ALGERIA", "DZ", "DZA", "012"),
            "EC" => array("ECUADOR", "EC", "ECU", "218"),
            "EE" => array("ESTONIA", "EE", "EST", "233"),
            "EG" => array("EGYPT", "EG", "EGY", "818"),
            "EH" => array("WESTERN SAHARA", "EH", "ESH", "732"),
            "ER" => array("ERITREA", "ER", "ERI", "232"),
            "ES" => array("SPAIN", "ES", "ESP", "724"),
            "ET" => array("ETHIOPIA", "ET", "ETH", "210"),
            "FI" => array("FINLAND", "FI", "FIN", "246"),
            "FJ" => array("FIJI", "FJ", "FJI", "242"),
            "FK" => array("FALKLAND ISLANDS (MALVINAS)", "FK", "FLK", "238"),
            "FM" => array("MICRONESIA, FEDERATED STATES OF", "FM", "FSM", "583"),
            "FO" => array("FAROE ISLANDS", "FO", "FRO", "234"),
            "FR" => array("FRANCE", "FR", "FRA", "250"),
            "FX" => array("FRANCE, METROPOLITAN", "FX", "FXX", "249"),
            "GA" => array("GABON", "GA", "GAB", "266"),
            "GB" => array("UNITED KINGDOM", "GB", "GBR", "826"),
            "GD" => array("GRENADA", "GD", "GRD", "308"),
            "GE" => array("GEORGIA", "GE", "GEO", "268"),
            "GF" => array("FRENCH GUIANA", "GF", "GUF", "254"),
            "GH" => array("GHANA", "GH", "GHA", "288"),
            "GI" => array("GIBRALTAR", "GI", "GIB", "292"),
            "GL" => array("GREENLAND", "GL", "GRL", "304"),
            "GM" => array("GAMBIA", "GM", "GMB", "270"),
            "GN" => array("GUINEA", "GN", "GIN", "324"),
            "GP" => array("GUADELOUPE", "GP", "GLP", "312"),
            "GQ" => array("EQUATORIAL GUINEA", "GQ", "GNQ", "226"),
            "GR" => array("GREECE", "GR", "GRC", "300"),
            "GT" => array("GUATEMALA", "GT", "GTM", "320"),
            "GU" => array("GUAM", "GU", "GUM", "316"),
            "GW" => array("GUINEA-BISSAU", "GW", "GNB", "624"),
            "GY" => array("GUYANA", "GY", "GUY", "328"),
            "HK" => array("HONG KONG", "HK", "HKG", "344"),
            "HM" => array("HEARD ISLAND & MCDONALD ISLANDS", "HM", "HMD", "334"),
            "HN" => array("HONDURAS", "HN", "HND", "340"),
            "HR" => array("CROATIA (local name: Hrvatska)", "HR", "HRV", "191"),
            "HT" => array("HAITI", "HT", "HTI", "332"),
            "HU" => array("HUNGARY", "HU", "HUN", "348"),
            "ID" => array("INDONESIA", "ID", "IDN", "360"),
            "IE" => array("IRELAND", "IE", "IRL", "372"),
            "IL" => array("ISRAEL", "IL", "ISR", "376"),
            "IN" => array("INDIA", "IN", "IND", "356"),
            "IO" => array("BRITISH INDIAN OCEAN TERRITORY", "IO", "IOT", "086"),
            "IQ" => array("IRAQ", "IQ", "IRQ", "368"),
            "IR" => array("IRAN, ISLAMIC REPUBLIC OF", "IR", "IRN", "364"),
            "IS" => array("ICELAND", "IS", "ISL", "352"),
            "IT" => array("ITALY", "IT", "ITA", "380"),
            "JM" => array("JAMAICA", "JM", "JAM", "388"),
            "JO" => array("JORDAN", "JO", "JOR", "400"),
            "JP" => array("JAPAN", "JP", "JPN", "392"),
            "KE" => array("KENYA", "KE", "KEN", "404"),
            "KG" => array("KYRGYZSTAN", "KG", "KGZ", "417"),
            "KH" => array("CAMBODIA", "KH", "KHM", "116"),
            "KI" => array("KIRIBATI", "KI", "KIR", "296"),
            "KM" => array("COMOROS", "KM", "COM", "174"),
            "KN" => array("SAINT KITTS AND NEVIS", "KN", "KNA", "659"),
            "KP" => array("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KP", "PRK", "408"),
            "KR" => array("KOREA, REPUBLIC OF", "KR", "KOR", "410"),
            "KW" => array("KUWAIT", "KW", "KWT", "414"),
            "KY" => array("CAYMAN ISLANDS", "KY", "CYM", "136"),
            "KZ" => array("KAZAKHSTAN", "KZ", "KAZ", "398"),
            "LA" => array("LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LA", "LAO", "418"),
            "LB" => array("LEBANON", "LB", "LBN", "422"),
            "LC" => array("SAINT LUCIA", "LC", "LCA", "662"),
            "LI" => array("LIECHTENSTEIN", "LI", "LIE", "438"),
            "LK" => array("SRI LANKA", "LK", "LKA", "144"),
            "LR" => array("LIBERIA", "LR", "LBR", "430"),
            "LS" => array("LESOTHO", "LS", "LSO", "426"),
            "LT" => array("LITHUANIA", "LT", "LTU", "440"),
            "LU" => array("LUXEMBOURG", "LU", "LUX", "442"),
            "LV" => array("LATVIA", "LV", "LVA", "428"),
            "LY" => array("LIBYAN ARAB JAMAHIRIYA", "LY", "LBY", "434"),
            "MA" => array("MOROCCO", "MA", "MAR", "504"),
            "MC" => array("MONACO", "MC", "MCO", "492"),
            "MD" => array("MOLDOVA, REPUBLIC OF", "MD", "MDA", "498"),
            "MG" => array("MADAGASCAR", "MG", "MDG", "450"),
            "MH" => array("MARSHALL ISLANDS", "MH", "MHL", "584"),
            "MK" => array("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "MK", "MKD", "807"),
            "ML" => array("MALI", "ML", "MLI", "466"),
            "MM" => array("MYANMAR", "MM", "MMR", "104"),
            "MN" => array("MONGOLIA", "MN", "MNG", "496"),
            "MO" => array("MACAU", "MO", "MAC", "446"),
            "MP" => array("NORTHERN MARIANA ISLANDS", "MP", "MNP", "580"),
            "MQ" => array("MARTINIQUE", "MQ", "MTQ", "474"),
            "MR" => array("MAURITANIA", "MR", "MRT", "478"),
            "MS" => array("MONTSERRAT", "MS", "MSR", "500"),
            "MT" => array("MALTA", "MT", "MLT", "470"),
            "MU" => array("MAURITIUS", "MU", "MUS", "480"),
            "MV" => array("MALDIVES", "MV", "MDV", "462"),
            "MW" => array("MALAWI", "MW", "MWI", "454"),
            "MX" => array("MEXICO", "MX", "MEX", "484"),
            "MY" => array("MALAYSIA", "MY", "MYS", "458"),
            "MZ" => array("MOZAMBIQUE", "MZ", "MOZ", "508"),
        );
    }

    private static function getCountriesNToZ(): array
    {
        return array(
            "NA" => array("NAMIBIA", "NA", "NAM", "516"),
            "NC" => array("NEW CALEDONIA", "NC", "NCL", "540"),
            "NE" => array("NIGER", "NE", "NER", "562"),
            "NF" => array("NORFOLK ISLAND", "NF", "NFK", "574"),
            "NG" => array("NIGERIA", "NG", "NGA", "566"),
            "NI" => array("NICARAGUA", "NI", "NIC", "558"),
            "NL" => array("NETHERLANDS", "NL", "NLD", "528"),
            "NO" => array("NORWAY", "NO", "NOR", "578"),
            "NP" => array("NEPAL", "NP", "NPL", "524"),
            "NR" => array("NAURU", "NR", "NRU", "520"),
            "NU" => array("NIUE", "NU", "NIU", "570"),
            "NZ" => array("NEW ZEALAND", "NZ", "NZL", "554"),
            "OM" => array("OMAN", "OM", "OMN", "512"),
            "PA" => array("PANAMA", "PA", "PAN", "591"),
            "PE" => array("PERU", "PE", "PER", "604"),
            "PF" => array("FRENCH POLYNESIA", "PF", "PYF", "258"),
            "PG" => array("PAPUA NEW GUINEA", "PG", "PNG", "598"),
            "PH" => array("PHILIPPINES", "PH", "PHL", "608"),
            "PK" => array("PAKISTAN", "PK", "PAK", "586"),
            "PL" => array("POLAND", "PL", "POL", "616"),
            "PM" => array("SAINT PIERRE AND MIQUELON", "PM", "SPM", "666"),
            "PN" => array("PITCAIRN", "PN", "PCN", "612"),
            "PR" => array("PUERTO RICO", "PR", "PRI", "630"),
            "PT" => array("PORTUGAL", "PT", "PRT", "620"),
            "PW" => array("PALAU", "PW", "PLW", "585"),
            "PY" => array("PARAGUAY", "PY", "PRY", "600"),
            "QA" => array("QATAR", "QA", "QAT", "634"),
            "RE" => array("REUNION", "RE", "REU", "638"),
            "RO" => array("ROMANIA", "RO", "ROU", "642"),
            "RS" => array("SERBIA", "RS", "SRB", "688"),
            "RU" => array("RUSSIAN FEDERATION", "RU", "RUS", "643"),
            "RW" => array("RWANDA", "RW", "RWA", "646"),
            "SA" => array("SAUDI ARABIA", "SA", "SAU", "682"),
            "SB" => array("SOLOMON ISLANDS", "SB", "SLB", "90"),
            "SC" => array("SEYCHELLES", "SC", "SYC", "690"),
            "SD" => array("SUDAN", "SD", "SDN", "736"),
            "SE" => array("SWEDEN", "SE", "SWE", "752"),
            "SG" => array("SINGAPORE", "SG", "SGP", "702"),
            "SH" => array("SAINT HELENA", "SH", "SHN", "654"),
            "SI" => array("SLOVENIA", "SI", "SVN", "705"),
            "SJ" => array("SVALBARD AND JAN MAYEN ISLANDS", "SJ", "SJM", "744"),
            "SK" => array("SLOVAKIA (Slovak Republic)", "SK", "SVK", "703"),
            "SL" => array("SIERRA LEONE", "SL", "SLE", "694"),
            "SM" => array("SAN MARINO", "SM", "SMR", "674"),
            "SN" => array("SENEGAL", "SN", "SEN", "686"),
            "SO" => array("SOMALIA", "SO", "SOM", "706"),
            "SR" => array("SURINAME", "SR", "SUR", "740"),
            "ST" => array("SAO TOME AND PRINCIPE", "ST", "STP", "678"),
            "SV" => array("EL SALVADOR", "SV", "SLV", "222"),
            "SY" => array("SYRIAN ARAB REPUBLIC", "SY", "SYR", "760"),
            "SZ" => array("SWAZILAND", "SZ", "SWZ", "748"),
            "TC" => array("TURKS AND CAICOS ISLANDS", "TC", "TCA", "796"),
            "TD" => array("CHAD", "TD", "TCD", "148"),
            "TF" => array("FRENCH SOUTHERN TERRITORIES", "TF", "ATF", "260"),
            "TG" => array("TOGO", "TG", "TGO", "768"),
            "TH" => array("THAILAND", "TH", "THA", "764"),
            "TJ" => array("TAJIKISTAN", "TJ", "TJK", "762"),
            "TK" => array("TOKELAU", "TK", "TKL", "772"),
            "TL" => array("EAST TIMOR", "TL", "TLS", "626"),
            "TM" => array("TURKMENISTAN", "TM", "TKM", "795"),
            "TN" => array("TUNISIA", "TN", "TUN", "788"),
            "TO" => array("TONGA", "TO", "TON", "776"),
            "TR" => array("TURKEY", "TR", "TUR", "792"),
            "TT" => array("TRINIDAD AND TOBAGO", "TT", "TTO", "780"),
            "TV" => array("TUVALU", "TV", "TUV", "798"),
            "TW" => array("TAIWAN, PROVINCE OF CHINA", "TW", "TWN", "158"),
            "TZ" => array("TANZANIA, UNITED REPUBLIC OF", "TZ", "TZA", "834"),
            "UA" => array("UKRAINE", "UA", "UKR", "804"),
            "UG" => array("UGANDA", "UG", "UGA", "800"),
            "UM" => array("UNITED STATES MINOR OUTLYING ISLANDS", "UM", "UMI", "581"),
            "US" => array("UNITED STATES", "US", "USA", "840"),
            "UY" => array("URUGUAY", "UY", "URY", "858"),
            "UZ" => array("UZBEKISTAN", "UZ", "UZB", "860"),
            "VA" => array("VATICAN CITY STATE (HOLY SEE)", "VA", "VAT", "336"),
            "VC" => array("SAINT VINCENT AND THE GRENADINES", "VC", "VCT", "670"),
            "VE" => array("VENEZUELA", "VE", "VEN", "862"),
            "VG" => array("VIRGIN ISLANDS (BRITISH)", "VG", "VGB", "92"),
            "VI" => array("VIRGIN ISLANDS (U.S.)", "VI", "VIR", "850"),
            "VN" => array("VIET NAM", "VN", "VNM", "704"),
            "VU" => array("VANUATU", "VU", "VUT", "548"),
            "WF" => array("WALLIS AND FUTUNA ISLANDS", "WF", "WLF", "876"),
            "WS" => array("SAMOA", "WS", "WSM", "882"),
            "YE" => array("YEMEN", "YE", "YEM", "887"),
            "YT" => array("MAYOTTE", "YT", "MYT", "175"),
            "YU" => array("YUGOSLAVIA", "YU", "YUG", "891"),
            "ZA" => array("SOUTH AFRICA", "ZA", "ZAF", "710"),
            "ZM" => array("ZAMBIA", "ZM", "ZMB", "894"),
            "ZR" => array("ZAIRE", "ZR", "ZAR", "180"),
            "ZW" => array("ZIMBABWE", "ZW", "ZWE", "716"),
        );
    }

}
