<?php
/*
 * Copyright (c) 2021 PayGate (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */
?>
<h2><?php echo $this->escapeHtml( $this->getMessage() ); ?></h2>
<p>Redirecting to PayGate...</p>
<form name="<?php echo $this->escapeHtml( $this->getName() ); ?>"
      id="<?php echo $this->escapeHtml( $this->getId() ); ?>"
      action="<?php echo $this->escapeHtml( $this->getFormAction() ); ?>"
      method="post" class="multicheckout">
    <?php foreach ( $this->getFormData() as $item => $value ): ?>
        <input type="hidden" name="<?php echo $this->escapeHtml( $item ); ?>" value="<?php echo $this->escapeHtml( $value ); ?>" size="200">
    <?php endforeach;?>
    <button type="submit" class="action primary">
        Click here if you are not redirected within 10 seconds...
    </button>
</form>
<?php echo $this->getSubmitForm(); ?>
