<?php
/*
 * Copyright (c) 2023 Payfast (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */

?>
<?php
/** @noinspection PhpUndefinedVariableInspection */
if ($instructions = $block->getMethod()->getInstructions()): ?>
    <div class="items <?=
    $block->escapeHtml($block->getMethodCode()) ?> instructions agreement content" id="payment_form_<?=
    $block->escapeHtml($block->getMethodCode()) ?>" style="display: none;">
        <?=
        $block->escapeHtml(nl2br($instructions))?>
    </div>
    <?php
endif; ?>
